name: books-prod

services:
  database:
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql

  backend:
    environment:
      DB_HOST: database
    restart: unless-stopped
    ports:
      - "${API_PORT}:${API_PORT}"

  frontend:
    build:
      target: production
    restart: unless-stopped
    ports:
      - "${UI_PORT}:${UI_PORT}"

volumes:
  postgres_data:
